version: '3.9'

services:
  backend:
    build: .
    container_name: ai_resume_backend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URI=mongodb://host.docker.internal:27017/ai_resume_matcher
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: unless-stopped

  frontend:
    build: ../frontend
    container_name: ai_resume_frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend
    restart: unless-stopped
